# Twitch authentication settings for pubsub and chat
# DO NOT SHARE WITH ANYONE
TARGET_CHANNEL = "prisonjoe" # YOUR CHANNEL NAME
STREAMER_OAUTH_TOKEN = "" 
STREAMER_CLIENT_ID = ""
STREAMER_CHANNEL_ID = "94243624"
BOT_OAUTH_TOKEN = ""
